name: PR - SDK build
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out Code
      uses: actions/checkout@v3

    - name: Installing .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.400
        include-prerelease: false

    - name: Restoring Packages
      run: dotnet restore ${{ github.workspace }}/src

    - name: Building Project(s)
      run: dotnet build ${{ github.workspace }}/src --no-restore

    - name: Publish MRLogs
      run: dotnet publish ${{ github.workspace }}/src/MRLogs/MRLogs.csproj -c Release -o ${{ github.workspace }}/bins/


    - name: Running Tests
      run: dotnet test ${{ github.workspace }}/src --no-build --verbosity normal